services:
  rasa:
    build: .  # از Dockerfile همین پوشه بیلد می‌کنه
    ports:
      - "5005:5005"
    volumes:
      - .:/app
    environment:
      - SQLALCHEMY_SILENCE_UBER_WARNING=1  # این هشدار رو ساکت می‌کنه
    command:
      - run
      - --enable-api
      - --cors
      - "*"
      - --debug

  actions:
    build: .  # همان Dockerfile برای action server
    ports:
      - "5055:5055"
    volumes:
      - ./actions:/app/actions
    command:
      - run
      - actions